server:
  port: 8083
spring:
  kafka:
    bootstrap-servers: kafka:9092

    consumer:
      group-id: ai-review-group-v2
      auto-offset-reset: latest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer

      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.ai_code_review_platform.ai_service.dto.PullRequestEventMessage

gemini:
  api-key: ${GEMINI_API_KEY}
  timeout-seconds: 60
  max-retries: 3
  initial-backoff-seconds: 2
  max-backoff-seconds: 15

bitbucket:
  api-url: https://api.bitbucket.org/2.0
  username: ${BITBUCKET_USERNAME}
  password: ${BITBUCKET_PASSWORD}
  timeout-seconds: 30
  max-retries: 3
  initial-backoff-seconds: 1
  max-backoff-seconds: 10
